adding eslint package and config
kalegd/DigitalBacon pull request #12
Opened 2023-12-06 12:52 UTC by laurittab

@kalegd 

Related issue: #7

![eslint](https://github.com/kalegd/DigitalBacon/assets/57863817/208e9de8-a1f6-48d2-a857-1b6e6064f8c7)

**Description**

Added ESLINT package and rules for character max, indents, semilcolons, dead code and arrow functions.

2023-12-07 18:23 UTC, kalegd requested changes

2023-12-07 18:23 UTC, kalegd commented on .eslintrc.json
> +    "indent": ["error", 4],
Ah I just realized I need to click `Finish your review` on GitHub for you to actually see this...

2023-12-07 18:49 UTC, laurittab commented
I just saw this option, I could have just clicked that.

![image](https://github.com/kalegd/DigitalBacon/assets/57863817/3bac04d4-4e3b-4ae5-b929-6354fb91eaf3)

2023-12-07 18:55 UTC, kalegd commented
> I just saw this option, I could have just clicked that.

Yea there are a ton of great features on GitHub! I'm finally trying to take the time to learn more of them myself

Anyways, thank you so much for being the first new contributor to this project 😃

2023-12-07 18:57 UTC, merged

2023-12-12 17:22 UTC, kalegd commented
@laurittab would you like to be added to the README's contributor list? I've just added a section for that

2023-12-12 17:57 UTC, laurittab commented
Yes pls that would be great 😀

2023-12-12 18:33 UTC, kalegd commented
@all-contributors please add @laurittab for infrastructure